cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: '2024.12'
  ai_chat_mode: openai
  ai_image_mode: none
  author_name: Chris
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: heroku_docker
  description: Life Care Planning Application for Kincaid Wolstein Vocational and
    Rehabilitation Services
  docker_setup: arm64
  domain_name: localhost:8000
  email: christophertskerritt@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: react
  github_username: cskerritt
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: SkillPlan
  project_slug: skillplan
  python_package_manager: uv
  standalone_front_end: vite
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_auth: n
  use_api_keys: y
  use_async_example: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: y
